### ISSUE TITLE
Template cannot be installed

### ISSUE THREAD

**Issue by DejanMilicic** [kant2002/FStarMSBuildSdk#1]
Running

```
dotnet new install FStarLang.DotNet.Common.ProjectTemplates.1.0::0.1.0 --nuget-source https://codevision.pkgs.visualstudio.com/FStarLang/_packaging/fstarlang/nuget/v3/index.json
```

as advised gives following error

```
Error: Invalid option(s):
  FStarLang.DotNet.Common.ProjectTemplates.1.0::0.0.9
```

**Comment by kant2002** [comment]
Can you try
```
dotnet new --install FStarLang.DotNet.Common.ProjectTemplates.1.0::0.1.0 --nuget-source https://codevision.pkgs.visualstudio.com/FStarLang/_packaging/fstarlang/nuget/v3/index.json
```

**Comment by DejanMilicic** [comment]
Yes, that works. You can merge #2

**Comment by kant2002** [comment]
Thanks. Would be nice to receive feedback on your experience, either here, or on Slack

**Comment by DejanMilicic** [comment]
Oh, I have a couple of issues now that I got everything working.
However, I suspect some of them are the result of my n00bness.

Can you please share the Slack invite with me so I can discuss them there?
For others, I will create them as issues.

**Comment by kant2002** [comment]
From https://www.fstar-lang.org/#introduction 
![image](https://user-images.githubusercontent.com/4257079/196364416-9a86bb8f-9e3f-49d4-ad98-f47ede79774c.png)

Click on this link https://aka.ms/JoinEverestSlack . I was under impression that you were FStar user, so you know about that slack.

**Comment by DejanMilicic** [comment]
I am aware of it, but you can join this Slack only if you have @google.com or @microsoft.com email address
So I was under the impression this is just an internal thing, not intended for public

**Comment by kant2002** [comment]
I have no affiliations with any institutions and I'm there, so you for sure free to join!

**Comment by DejanMilicic** [comment]
![image](https://user-images.githubusercontent.com/507133/196423089-b0079120-7e94-4104-b4d4-8c21f6290e10.png)

Look at the info at the bottom of the screenshot.
Any chance you could talk to Admin(s) concerning an invitation?

**Comment by kant2002** [comment]
Maybe this invite will do. 
https://join.slack.com/t/everestexpedition/shared_invite/zt-1hzrxbbp2-ubuxJfR5EkSuGdMWNVgUFw

will try to find official one if this would not works

**Comment by DejanMilicic** [comment]
First attempt with this alternative link gave me 401
On a second attempt, I managed to access it. 
Thank you!

**Comment by kant2002** [comment]
Fstar-hackery is default channel for F* where most activity happens
